apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-back
  template:
    metadata:
      labels:
        app: users-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: usersapp
          image: acrhcasamplega.azurecr.io/usersapp:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-back
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: users-back
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: users-back
                port:
                  number: 80