name: build_deploy_aks
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build the image"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrhcasamplega.azurecr.io/samplegha:${{ github.sha }}
          file: Dockerfile
